name: string_encryption
description: Cross-platform string encryption using common best-practices.
version: 1.0.2
homepage: https://github.com/turkialawlqy/string_encryption

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.12.0-0 <3.0.0'

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    android:
      package: com.github.turkialawlqy.flutterstringencryption
      pluginClass: FlutterStringEncryptionPlugin
