name: string_encryption
description: Cross-platform string encryption using common best-practices.
version: 2.0.4
homepage: https://github.com/turkialawlqy/string_encryption


environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.github.turkialawlqy.flutterstringencryption
        pluginClass: FlutterStringEncryptionPlugin
      ios:
        pluginClass: FlutterStringEncryptionPlugin